#!/bin/sh
[ -d dist ] && rm -r dist
npx ng build --prod --base-href ./ --deploy-url ./
mkdir dist/foobar
mv dist/* dist/foobar
cp -r dist/{foobar,baz}
sleep 3 && xdg-open http://localhost:4200/foobar &
caddy file-server --listen localhost:4200 --root dist
